import { z } from 'zod';

/**
 * Zod validation schema representing a scorecard generated by the Investment Scoring Agent.
 * Enforces integer bounds (0-100) and recommendation rules.
 */
export const scoringSchema = z.object({
  businessQuality: z.number({
    required_error: 'businessQuality is required',
    invalid_type_error: 'businessQuality must be an integer'
  }).int().min(0).max(100),

  growthPotential: z.number({
    required_error: 'growthPotential is required',
    invalid_type_error: 'growthPotential must be an integer'
  }).int().min(0).max(100),

  competitiveMoat: z.number({
    required_error: 'competitiveMoat is required',
    invalid_type_error: 'competitiveMoat must be an integer'
  }).int().min(0).max(100),

  financialStrength: z.number({
    required_error: 'financialStrength is required',
    invalid_type_error: 'financialStrength must be an integer'
  }).int().min(0).max(100),

  riskLevel: z.number({
    required_error: 'riskLevel is required',
    invalid_type_error: 'riskLevel must be an integer'
  }).int().min(0).max(100),

  overallScore: z.number({
    required_error: 'overallScore is required',
    invalid_type_error: 'overallScore must be an integer'
  }).int().min(0).max(100),

  confidence: z.number({
    required_error: 'confidence is required',
    invalid_type_error: 'confidence must be an integer'
  }).int().min(0).max(100),

  recommendation: z.enum(['INVEST', 'WATCH', 'PASS'], {
    required_error: 'recommendation is required',
    invalid_type_error: 'recommendation must be INVEST, WATCH, or PASS'
  })
}).refine((data) => {
  // Validate overallScore alignment with recommendation rules:
  // - overallScore >= 80 -> INVEST
  // - overallScore >= 60 and < 80 -> WATCH
  // - overallScore < 60 -> PASS
  const score = data.overallScore;
  const rec = data.recommendation;

  if (score >= 80) {
    return rec === 'INVEST';
  } else if (score >= 60) {
    return rec === 'WATCH';
  } else {
    return rec === 'PASS';
  }
}, {
  message: "Recommendation does not align with overallScore guidelines (Score >= 80 -> INVEST, Score >= 60 -> WATCH, Score < 60 -> PASS).",
  path: ['recommendation']
});
